### ISSUE TITLE
Extension fails with multiple root folders in Workspace

### ISSUE THREAD

**Issue by Offtree** [Dennitz/vscode-generact#3]
### Per: https://code.visualstudio.com/docs/extensionAPI/vscode-api
The current usage of `rootPath` is depreciated and should be switched to the first value of `workspaceFolders`.

As of now the extension just can't find any components.

**Comment by Dennitz** [comment]
Thanks for creating the issue!

Will look into this in the next few days.

**Comment by Dennitz** [comment]
Should be working now.

**Comment by diegohaz** [comment]
Hey, @Dennitz. Could you release new version?

**Comment by Dennitz** [comment]
It should already be released. The newest version is 1.0.2. 
Does it not work for you?

**Comment by diegohaz** [comment]
Ah, I see. The first step is different. 😅
Sorry about that, good job.
